### ISSUE TITLE
Add CI to project

### ISSUE THREAD

**Issue by ok2ju** [interviewr/interviewr-server#14]
Choose between `TravisCI` or `CircleCI`

**Comment by zmeecer** [comment]
Travis CI is from the box in GitHub integration
Also `Travis CI is focused on the open source market` and the most similar to GitLab CI which familiar for the maintainers

**Comment by zmeecer** [comment]
Reopen for adding CI script

**Comment by zmeecer** [comment]
Fixed in #16
