### ISSUE TITLE
Pass service configuration via docker volume

### ISSUE THREAD

**Issue by ok2ju** [interviewr/interviewr-server#15]
Maybe pass `config.json` via docker volume

**Comment by zmeecer** [comment]
Should it be ENV VARs?

**Comment by ok2ju** [comment]
We can still use [Viper](https://github.com/spf13/viper#working-with-environment-variables). It's in project deps.
[Docker ENV Variables](https://docs.docker.com/docker-cloud/getting-started/deploy-app/6_define_environment_variables/)
